version: "3.8"

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: studienprojekt_db
    ports:
      - "3307:3306"
    volumes:
      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - mysql-data:/var/lib/mysql

  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: studienprojekt_db
      MYSQL_PORT: 3306
    depends_on:
      - mysql

volumes:
  mysql-data:
